

select * from customer limit 20

-- 1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as reveniue
from customer
group by gender
-- 2. Which customers used a discount but still spent more than the average purchase amount?
-- discounts are supposed to reduce the spent,right?But some cutomer still spend more amt of money even when using discount
select customer_id,purchase_amount 
from  customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- 3. Which are the top 5 products with the highest average review rating?
-- Here we have to calculate average review rating of each product and then we have to 
-- find the top 5 products with the highest average review rating
-- Code:1
select item_purchased, AVG(review_rating) as "Average product Rating" 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
-- ################################
-- Avg(review_rating) this wont run in some version because while importing data from jupyter to postgresql
-- postgresql typecasted review rating column as double precision.
-- To calculate this we use Round function but ROUND function doesnt work in double precision so we do use
-- ###################################
--  #### ROUND function ##### AS shown below:
-- Code:2
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average product Rating" 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
-- So now in my case as i was using version 18 my code executed without round too.(That is Code 1)
-- Code 2 preferred then Code 1

-- 4. Compare the average purchase amounts between Standard and Express Shipping.
-- Single Quotes (') - String Literals: Used to enclose string values, date values, or textual data (e.g., 'Hello World').
-- Double Quotes (") - Identifiers: Used to enclose database object names like table names, column names, or aliases (e.g., "User Table").
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
-- OUTPUT exp: amount is higher for Express shipping than standard, so business should focus more on express shipping and other faster delivery options

-- 5. Do subscribed customers spend more on average and contribute more total revenue than non-subscribers?
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;
-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
-- ###############################
-- We are not looking for total discount, here we are calculating the total discount rate per product
-- Here, we have to see which product rely heavily on discount to sell
-- ###############################
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- 7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment and their total number of purchases.
-- Here we have used CTE
with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from  customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment 

-- 8. What are the top 3 most purchased products within each category?
-- here we will need a window function to rank products by total orders withing each category
-- Then we will pick the top 3 and we'll also need a CTE for this query as well
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count (customer_id)DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;
-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to be subscribers?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
-- 10. What is the revenue contribution of each age group?
-- It tells us which demographic  is most  valuable to the business
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc

